- hosts: all
  become: true

  pre_tasks:

    - name: test connectivity
      tags: always
      ping:

    - name: Update index repository
      tags: always
      apt:
        update_cache: yes
      when: ansible_distribution in ["Ubuntu", "Debian"] 


- hosts: all
  become: true
  roles:
    - create_user
    - configure_apache
    - setup_terraform 
    