- hosts: all
  become: true

  pre_tasks:

    - name: test connectivity
      tags: always
      ping:

    - name: Update index repository
      tags: always
      apt:
        update_cache: yes
      when: ansible_distribution in ["Ubuntu", "Debian"] 


- hosts: all
  become: true

  tasks:

    - name: Install apache2 package
      tags: apache2, ubuntu, apache
      apt:
        name: apache2
        state: latest
      when: ansible_distribution == "Ubuntu"


    - name: Add php support for apache2
      tags: apache2, ubuntu, apache
      apt:
        name: libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"
