---
# tasks file for setup_terraform
- name: Install unzip
  apt: 
    name: unzip 
    state: present

- name: Install terraform
  ansible.builtin.unarchive:
    src: https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes